"""empty message

Revision ID: 0389b16a7049
Revises: e304dbe84e59
Create Date: 2021-03-22 16:53:29.283373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0389b16a7049'
down_revision = 'e304dbe84e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('info_reservation', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'volunteers', 'reservations', ['info_reservation'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteers', type_='foreignkey')
    op.drop_column('volunteers', 'info_reservation')
    # ### end Alembic commands ###
