"""empty message

Revision ID: 75f1b8af5a72
Revises: 368d876d0d85
Create Date: 2021-04-27 20:42:40.944969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f1b8af5a72'
down_revision = '368d876d0d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('package_reviewed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'packages', ['package_reviewed_id'], ['id'])
    op.drop_constraint('packages_books_id_fkey', 'packages', type_='foreignkey')
    op.drop_column('packages', 'books_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('books_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('packages_books_id_fkey', 'packages', 'books', ['books_id'], ['id'])
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'package_reviewed_id')
    # ### end Alembic commands ###
