"""empty message

Revision ID: cdbda97cc65a
Revises: fe8de7f7cbb6
Create Date: 2021-04-13 22:35:25.620398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbda97cc65a'
down_revision = 'fe8de7f7cbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('village_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_village_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'villages', ['village_id'], ['id'])
    op.drop_column('users', 'village')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('village', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_village_fkey', 'users', 'villages', ['village'], ['id'])
    op.drop_column('users', 'village_id')
    # ### end Alembic commands ###
