"""empty message

Revision ID: e304dbe84e59
Revises: 86ecd9dfe80d
Create Date: 2021-03-22 16:50:34.854393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e304dbe84e59'
down_revision = '86ecd9dfe80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('volunteer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'volunteers', ['volunteer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'volunteer_id')
    # ### end Alembic commands ###
